### ISSUE TITLE
Umlaute im Rollenmenü

### ISSUE THREAD

**Issue by lasergraph** [alamos-gmbh/fe2-docker#5]
Umlaute werden im Rollenmenü micht korrekt dargestellt. Version: 2.29.530-STABLE

![grafik](https://github.com/alamos-gmbh/fe2-docker/assets/118357000/8c244e98-4a93-4daf-b596-6a6404d33d7e)

**Comment by alamos-gmbh** [comment]
Danke für die Meldung.
In der nächsten FE2 2.29 Stable korrigiert.
Außerhalb dieses Repositories.
