### ISSUE TITLE
nginx keeps crashing due to missing dhparams.pem

### ISSUE THREAD

**Issue by r1h4** [alamos-gmbh/fe2-docker#7]
Hi,
with certbot enabled the nginx-container keeps restarting due to the missing dhparams.pem. Commenting the line

>         ssl_dhparam /etc/letsencrypt/dhparam.pem;
in [nginx/fe2-ssl.conf](https://github.com/alamos-gmbh/fe2-docker/blob/main/nginx/fe2-ssl.conf) leads to a running container and everything works fine. After manually creating the dhparam.pem it works with ssl_dhparam enabled. Maybe the restarting container prohibited the creation of the dhparam.pem

**Comment by Finn0811** [comment]
Have you stopped the container while it was starting for the first time?
That could have caused an empty dhparam file and prevent the container from generating a new one. 

The readme already states that:
> ⌛ After starting an SSL enabled FE2 docker instance for the first time, it takes about 15-30 minutes to generate encryption specific parameters (DH parameters). This is normal. The progress can be visualized using docker logs -f fe2_nginx

**Comment by r1h4** [comment]
> Have you stopped the container while it was starting for the first time? That could have caused an empty dhparam file and prevent the container from generating a new one.
> 
> The readme already states that:
> 
> > hourglass After starting an SSL enabled FE2 docker instance for the first time, it takes about 15-30 minutes to generate encryption specific parameters (DH parameters). This is normal. The progress can be visualized using docker logs -f fe2_nginx

Yeah, that was the problem :) Thanks!
