### ISSUE TITLE
FE2 2.30 > docker-compose.yml.template

### ISSUE THREAD

**Issue by psychos4** [alamos-gmbh/fe2-docker#9]
Gibt es für die 2.30er Version noch eine angepasste docker-compose.yml.template oder einen branch? 
Mit der 2.30er wird ja die neue MongoDB Version 4 verwendet? Gibts diesbezüglich 2.29 auf 2.30 speziell was zu beachten?

**Comment by MrWeezle** [comment]
Erst, wenn die 2.30 als STABLE veröffentlicht ist, gibt es hier eine bereitgestellte Version.
